--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BALANCE
--------------------------------------------------------
  CREATE USER C##EPOLAT IDENTIFIED BY aassddff;
    GRANT CONNECT TO C##EPOLAT;
    GRANT CONNECT, RESOURCE, DBA TO C##EPOLAT;
    GRANT CREATE SESSION ,GRANT ANY PRIVILEGE TO C##EPOLAT;
    GRANT UNLIMITED TABLESPACE TO C##EPOLAT;

  CREATE TABLE "C##EPOLAT"."BALANCE" 
   (	"PAID" VARCHAR2(100 BYTE), 
	"FEE" VARCHAR2(100 BYTE), 
	"EXTRA" VARCHAR2(100 BYTE), 
	"CUSTOMERID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSE
--------------------------------------------------------

  CREATE TABLE "C##EPOLAT"."COURSE" 
   (	"CODE" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(30 BYTE), 
	"TYPE" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUSTOMER
--------------------------------------------------------

  CREATE TABLE "C##EPOLAT"."CUSTOMER" 
   (	"CUSTOMERID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"SURNAME" VARCHAR2(100 BYTE), 
	"GENDER" VARCHAR2(100 BYTE), 
	"BIRTHYEAR" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SECTION
--------------------------------------------------------

  CREATE TABLE "C##EPOLAT"."SECTION" 
   (	"SECTIONNUMBER" NUMBER, 
	"TIME" NUMBER, 
	"CODE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TAKES
--------------------------------------------------------

  CREATE TABLE "C##EPOLAT"."TAKES" 
   (	"SECNUMBER" NUMBER, 
	"CUSTOMERID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAINER
--------------------------------------------------------

  CREATE TABLE "C##EPOLAT"."TRAINER" 
   (	"TRAINERID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"SURNAME" VARCHAR2(100 BYTE), 
	"SECTIONNUMBER" NUMBER, 
	"PROFESSION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##EPOLAT.BALANCE
SET DEFINE OFF;
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('550','200','350','56548629644');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('400','200','400','37846334608');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('500','200','300','92085739083');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('320','200','120','62497875094');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('300','200','100','43774039075');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('500','200','450','11200383195');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('1000','200','950','55379016254');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('450','200','320','15282018920');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('300','200','500','24850746998');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('800','200','600','94941316601');
Insert into C##EPOLAT.BALANCE (PAID,FEE,EXTRA,CUSTOMERID) values ('180','200','0','15469854126');
REM INSERTING into C##EPOLAT.COURSE
SET DEFINE OFF;
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('SA-101','samba','group');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('Y-101','yoga','group');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('Z-101','zumba','group');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('C-101','crossfit','personal');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('P-101','pilates','group');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('T-101','tennis','personal');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('B-101','basketball','group');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('F-101','football','group');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('V-101','volleyball','group');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('Sq-101','squash','personal');
Insert into C##EPOLAT.COURSE (CODE,NAME,TYPE) values ('S-101','swim','personal');
REM INSERTING into C##EPOLAT.CUSTOMER
SET DEFINE OFF;
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('56548629644','Jade','Lapworth','Female','2009');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('37846334608','Cyrill','Bambrough','Male','1995');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('92085739083','Lurette','MacWhirter','Female','1996');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('62497875094','Graham','Kiln','Male','2010');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('43774039075','See','Biasi','Male','2002');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('11200383195','Antony','Paute','Male','1994');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('55379016254','Sonia','Palluschek','Female','1999');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('15282018920','Tomas','Van Son','Male','1991');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('24850746998','Wally','Gorwood','Female','1999');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('94941316601','Jedd','Paynes','Male','2011');
Insert into C##EPOLAT.CUSTOMER (CUSTOMERID,NAME,SURNAME,GENDER,BIRTHYEAR) values ('15469854126','Jon','Snow','Male','1980');
REM INSERTING into C##EPOLAT.SECTION
SET DEFINE OFF;
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('1','3','Y-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('2','5','Z-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('3','1','C-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('4','3','P-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('5','5','T-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('6','6','B-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('7','2','F-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('8','5','V-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('9','3','Sq-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('10','1','S-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('11','1','C-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('12','3','P-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('13','6','B-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('14','6','B-101');
Insert into C##EPOLAT.SECTION (SECTIONNUMBER,TIME,CODE) values ('15','3','Sq-101');
REM INSERTING into C##EPOLAT.TAKES
SET DEFINE OFF;
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('6','11200383195');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('11','55379016254');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('3','56548629644');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('10','37846334608');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('7','92085739083');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('1','62497875094');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('4','43774039075');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('9','11200383195');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('8','55379016254');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('2','15282018920');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('5','24850746998');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('6','94941316601');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('9','56548629644');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('10','55379016254');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('11','24850746998');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('12','92085739083');
Insert into C##EPOLAT.TAKES (SECNUMBER,CUSTOMERID) values ('5','94941316601');
REM INSERTING into C##EPOLAT.TRAINER
SET DEFINE OFF;
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('14462839072','Ambrosio','Espadas','1','yoga');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('23757417799','Marcelle','Davoren','2','zumba');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('34449406368','Boycie','Rolls','3','crossfit');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('51027571318','Trish','Orrobin','4','pilates');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('18468901841','Vinson','Swindells','5','tennis');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('81032408559','Vivyan','Gouldthorpe','6','basketball');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('15737492798','Karyl','Rossetti','7','football');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('19499730698','Maryjane','Lemarie','8','volleyball');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('91934155563','Jessalyn','Eatttok','9','squash');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('40150721946','Ines','Blincko','10','swim');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('94358162597','Süleyman','Karabacak','11','crossfit');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('63519834621','Bilgin ','Avenoðlu','12','pilates');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('46849512847','Tayfun','Küçükyýlmaz','13','basketball');
Insert into C##EPOLAT.TRAINER (TRAINERID,NAME,SURNAME,SECTIONNUMBER,PROFESSION) values ('64982435610','Gizem','Kayar','14','basketball');
--------------------------------------------------------
--  DDL for Index COURSE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EPOLAT"."COURSE_PK" ON "C##EPOLAT"."COURSE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CUSTOMER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EPOLAT"."CUSTOMER_PK" ON "C##EPOLAT"."CUSTOMER" ("CUSTOMERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SECTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EPOLAT"."SECTION_PK" ON "C##EPOLAT"."SECTION" ("SECTIONNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SECTION_UN
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EPOLAT"."SECTION_UN" ON "C##EPOLAT"."SECTION" ("CODE", "SECTIONNUMBER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TRAINER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##EPOLAT"."TRAINER_PK" ON "C##EPOLAT"."TRAINER" ("TRAINERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BALANCE
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."BALANCE" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COURSE
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."COURSE" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "C##EPOLAT"."COURSE" ADD CONSTRAINT "COURSE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMER
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."CUSTOMER" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
  ALTER TABLE "C##EPOLAT"."CUSTOMER" ADD CONSTRAINT "CUSTOMER_PK" PRIMARY KEY ("CUSTOMERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SECTION
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."SECTION" MODIFY ("SECTIONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##EPOLAT"."SECTION" MODIFY ("CODE" NOT NULL ENABLE);
  ALTER TABLE "C##EPOLAT"."SECTION" ADD CONSTRAINT "SECTION_PK" PRIMARY KEY ("SECTIONNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##EPOLAT"."SECTION" ADD CONSTRAINT "SECTION_UN" UNIQUE ("CODE", "SECTIONNUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TAKES
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."TAKES" MODIFY ("SECNUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##EPOLAT"."TAKES" MODIFY ("CUSTOMERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAINER
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."TRAINER" MODIFY ("SECTIONNUMBER" NOT NULL ENABLE);
  ALTER TABLE "C##EPOLAT"."TRAINER" ADD CONSTRAINT "TRAINER_PK" PRIMARY KEY ("TRAINERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table BALANCE
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."BALANCE" ADD CONSTRAINT "BALANCE_CUSTOMER_FK" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "C##EPOLAT"."CUSTOMER" ("CUSTOMERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SECTION
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."SECTION" ADD CONSTRAINT "SECTION_COURSE_FK" FOREIGN KEY ("CODE")
	  REFERENCES "C##EPOLAT"."COURSE" ("CODE") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TAKES
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."TAKES" ADD CONSTRAINT "TAKES_SECTION_FK" FOREIGN KEY ("SECNUMBER")
	  REFERENCES "C##EPOLAT"."SECTION" ("SECTIONNUMBER") ON DELETE CASCADE ENABLE;
  ALTER TABLE "C##EPOLAT"."TAKES" ADD CONSTRAINT "TAKES_CUSTOMER_FK" FOREIGN KEY ("CUSTOMERID")
	  REFERENCES "C##EPOLAT"."CUSTOMER" ("CUSTOMERID") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAINER
--------------------------------------------------------

  ALTER TABLE "C##EPOLAT"."TRAINER" ADD CONSTRAINT "TRAINER_SECTION_FK" FOREIGN KEY ("SECTIONNUMBER")
	  REFERENCES "C##EPOLAT"."SECTION" ("SECTIONNUMBER") ON DELETE CASCADE ENABLE;

CREATE VIEW "C##EPOLAT".groupCourses AS
SELECT type,name 
    from "C##EPOLAT".course 
    where type = 'group';

CREATE SEQUENCE "C##EPOLAT".seq1
start with 1
increment by 1
maxVALUE 50
cycle;
